[package]
name = "aoc-2016"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
log = "0.4.20"
md5 = "0.7.0"
regex = "1.10.3"
simplelog = "0.12.1"
thousands = "0.2.0"
